language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - pip install flake8
before_script:
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
script: make test
